import axios from 'axios'
import React,{useEffect,useState} from 'react'
import CurrencyTable from '../../components/currencyTable/CurrencyTable'
import Header from "../../components/homeHeader/Header"
import './styles.css'


const Analytics = () => {

const [data,setData] = useState([])
const [marketData, setMarketData] = useState([])
const [marketDataFlag, setMarketDataFlag] = useState(false)
const [pageNum, setPageNum] = useState(0)
const [loader, setLoader] = useState(false)
const [marketPages, setMarketPages] = useState(0)
const [tokenFlag ,setTokenFlag] = useState(0)
const [marketFlag, setMarketFlag] = useState(0)

const getAnalytics = () => {
    console.log('getting')
    setLoader(true)
    axios.get(`https://www.sushi.com/analytics/api/tokens?orderBy=liquidityUSD&orderDirection=desc&pagination={%22pageIndex%22:${pageNum},%22pageSize%22:20}&networks=[1,42161,43114,1285,100,250,56,42220,122,1284,42170,137,288,10,1088,2222]`).then((response)=>{
        
    console.log("listing all Data: ", response.data);
    setMarketDataFlag(false)
    setLoader(false)
    setData(response.data)
    // setMarketPages(0)
    
    })
    console.log(data,'end')
}

const getTopMarkets = () => {
    console.log('trying')
    setLoader(true)
    axios.get(`https://www.sushi.com/analytics/api/pools?orderBy=liquidityUSD&orderDirection=desc&pagination={%22pageIndex%22:${marketPages},%22pageSize%22:20}&networks=[1,42161,43114,1285,100,250,56,42220,122,1284,42170,137,288,10,1088,2222]`)
    .then((response)=>{
        setMarketData(response.data)
        setMarketDataFlag(true)
        setLoader(false)
        // setPageNum(0)
    })
}

useEffect(()=>{
getAnalytics()
},[pageNum])

useEffect(()=>{
getTopMarkets()
},[marketPages])

console.log(data,'-----##')

return (
    <div className='mainContainer'>
        <Header/>

        
        <div className='heading'>
            Anaylytics
        </div>
        <div className='subHeading'>
        Analytics platform for tracking the liquidity, volume, and fees generated by Fibi Swap.
        </div>
        <div className='buttonContainer'>
        <div className='tokenButtons' 
        onClick={getTopMarkets}
        >
                Top Markets
        </div>
        <div className='tokenButtons'
        onClick={getAnalytics}
        >
            Top Token
        </div>
        </div>
        <div className='subHeading'>
        Following are the list of Top {marketDataFlag === true ? 'Markets' : 'Tokens'}
        </div>
        <div style={{padding:10}}>
        <CurrencyTable 
        data={marketDataFlag === true ? marketData : data} 
        marketFlag = {marketDataFlag} 
        setPageNum={setPageNum}
        pageNum = {pageNum}
        loader = {loader}
        getAnalytics={getAnalytics}
        marketTokenFlag={marketFlag}
        tokenFlag={tokenFlag}
        getTopMarkets = {getTopMarkets}
        setMarketPages = {setMarketPages}
        marketPages = {marketPages}
        />
        </div>
        <div>
        </div>
        
    </div>
  )
}

export default Analytics