import axios from 'axios'
import React,{useEffect,useState} from 'react'
import CurrencyTable from '../../components/currencyTable/CurrencyTable'
import Header from "../../components/homeHeader/Header"
import './styles.css'


const Analytics = () => {

const [data,setData] = useState([])
const [marketData, setMarketData] = useState([])
const [marketDataFlag, setMarketDataFlag] = useState(false)
const [pageNum, setPageNum] = useState(0)
const [loader, setLoader] = useState(false)
const [marketPages, setMarketPages] = useState(0)
const [marketCount, setMarketCount] = useState(0)
const [tokenCount, setTokenCount] = useState(0)

const getAnalytics = () => {
    setLoader(true)
    axios.get(`https://www.sushi.com/analytics/api/tokens?orderBy=liquidityUSD&orderDirection=desc&pagination={%22pageIndex%22:${pageNum},%22pageSize%22:20}&networks=[1,42161,43114,1285,100,250,56,42220,122,1284,42170,137,288,10,1088,2222]`).then((response)=>{

    setMarketDataFlag(false)
    setLoader(false)
    setData(response.data)
    
    })
}

const getTopMarkets = () => {
    setLoader(true)
    axios.get(`https://www.sushi.com/analytics/api/pools?orderBy=liquidityUSD&orderDirection=desc&pagination={%22pageIndex%22:${marketPages},%22pageSize%22:20}&networks=[1,42161,43114,1285,100,250,56,42220,122,1284,42170,137,288,10,1088,2222]`)
    .then((response)=>{

        setMarketDataFlag(true)
        setLoader(false)
        setMarketData(response.data)
        console.log(marketPages,data.length,'112')
    })
}

useEffect(()=>{
getAnalytics()
},[pageNum])

useEffect(()=>{
getTopMarkets()
},[marketPages])


const handleMarketButton = () => {

    getTopMarkets()
    setMarketCount(1)
    setTokenCount(0)
}

const handleAnalyticButton = () => {
    getAnalytics()
    setTokenCount(1)
    setMarketCount(0)
}
  return (

   

    <div className='mainContainer'>
        <Header/>

        
        <div className='heading'>
            Anaylytics
        </div>
        <div className='subHeading'>
        Analytics platform for tracking the liquidity, volume, and fees generated by Fibi Swap.
        </div>
        <div className='buttonContainer'>
        <div className='tokenButtons' 
        onClick={handleMarketButton}
        >
                Top Markets
        </div>
        <div className='tokenButtons'
        onClick={handleAnalyticButton}
        >
            Top Token
        </div>
        </div>
        <div className='subHeading'>
        Following are the list of Top {marketDataFlag === true ? 'Markets' : 'Tokens'}
        </div>
        <div style={{padding:10}}>
        <CurrencyTable 
        data={marketDataFlag === true ? marketData : data} 
        marketFlag = {marketDataFlag} 
        setPageNum={setPageNum}
        pageNum = {pageNum}
        loader = {loader}
        getAnalytics={getAnalytics}
        getTopMarkets = {getTopMarkets}
        setMarketPages = {setMarketPages}
        marketPages = {marketPages}
        marketCount={marketCount}
        tokenCount = {tokenCount}
        
        />
        </div>
        <div>
        </div>
        
    </div>
  )
}

export default Analytics